//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Reports {
    
    public partial class crys_payrolldetail_report {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadScriptManager ScriptManager;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.WebControls.DropDownList cmbYear;
        protected System.Web.UI.HtmlControls.HtmlSelect cmbEmp;
        protected System.Web.UI.HtmlControls.HtmlSelect cmbmonth;
        protected System.Web.UI.HtmlControls.HtmlSelect cmbmonthto;
        protected System.Web.UI.WebControls.Button bnsubmit;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
    }
}
