//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Reports {

    public partial class CustomReportClaims
    {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm employeeform;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected Telerik.Web.UI.RadFormDecorator RadFormDecorator1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.WebControls.ImageButton btnExportWord;
        protected System.Web.UI.WebControls.ImageButton btnExportExcel;
        protected System.Web.UI.WebControls.ImageButton btnExportPdf;
        protected System.Web.UI.WebControls.PlaceHolder PlaceHolder1;
        protected Telerik.Web.UI.RadAjaxManager RadAjaxManager1;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
    }
}
