USETEXTLINKS = 1
STARTALLOPEN = 0
HIGHLIGHT = 1
HIGHLIGHT_BG = '#808080'
ICONPATH = 'images/'
GLOBALTARGET = 'R'
foldersTree = gFld('', '')
foldersTree.iconSrc = ICONPATH + 'ftv2blank.gif'
foldersTree.treeID = 'Tree1'

docAux = insDoc(foldersTree, gLnk('R', '&nbsp;Welcome&nbsp;', 'Welcome.htm'))
docAux = insDoc(foldersTree, gLnk('R', '&nbsp;Modules&nbsp;', 'modules.htm'))
docAux = insDoc(foldersTree, gLnk('R', '&nbsp;Customer&nbsp;Support&nbsp;&nbsp;', 'Ask.htm'))
docAux = insDoc(foldersTree, gLnk('R', '&nbsp;Minimum&nbsp;System&nbsp;Requirements&nbsp;', 'minimum_system_requirements.htm'))
docAux = insDoc(foldersTree, gLnk('R', '&nbsp;End&nbsp;User&nbsp;License&nbsp;Agreement&nbsp;', 'end_user_license_agreement.htm'))
xemployee_management = insFld(foldersTree, gFld('&nbsp;Employee&nbsp;Management&nbsp;', 'employee_management.htm'))
xemployee_management.iconSrc = "images/pageicon_folder.gif"
xemployee_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;are&nbsp;employee&nbsp;groups?&nbsp;', 'what_are_employee_groups_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;Why&nbsp;we&nbsp;need&nbsp;different&nbsp;Employee&nbsp;groups?&nbsp;', 'why_we_need_different_employee_groups_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;add&nbsp;an&nbsp;employee?&nbsp;', 'how_to_add_an_employee_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;information&nbsp;can&nbsp;be&nbsp;stored&nbsp;for&nbsp;an&nbsp;employee?&nbsp;', 'what_information_can_be_stored_for_an_employee_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;kind&nbsp;of&nbsp;employees&nbsp;can&nbsp;be&nbsp;added?&nbsp;', 'what_kind_of_employees_can_be_added_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;kind&nbsp;of&nbsp;payment&nbsp;modes&nbsp;are&nbsp;available?&nbsp;', 'what_kind_of_payment_modes_are_available_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;type&nbsp;of&nbsp;&nbsp;CPF&nbsp;contribution&nbsp;sectors&nbsp;are&nbsp;supported?&nbsp;', 'what_type_of_sector_is_supported_for_cpf_contribution_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;image&nbsp;formats&nbsp;are&nbsp;supported&nbsp;for&nbsp;employee&nbsp;photo?&nbsp;', 'what_image_formats_are_supported_for_employee_photo_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;file&nbsp;formats&nbsp;are&nbsp;supported&nbsp;for&nbsp;uploading&nbsp;employee&nbsp;documents?&nbsp;', 'what_file_formats_are_supported_for_uploading_employee_documents_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;view&nbsp;all&nbsp;Active&nbsp;employees?&nbsp;', 'what_is_the_function_of_show_all_employees_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;view&nbsp;Terminated&nbsp;employees?&nbsp;', 'how_to_view_all_terminated_employees_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;view&nbsp;all&nbsp;Terminated&nbsp;as&nbsp;well&nbsp;as&nbsp;active&nbsp;employees?&nbsp;', 'how_to_view_all_terminated_as_well_as_active_employees_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;export&nbsp;employee&nbsp;info?&nbsp;', 'how_to_export_employee_info_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;search&nbsp;a&nbsp;particular&nbsp;employee&nbsp;from&nbsp;the&nbsp;list?&nbsp;', 'how_can_i_search_a_particular_employee_from_the_list_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Edit&nbsp;the&nbsp;particulars&nbsp;of&nbsp;an&nbsp;employee?&nbsp;', 'how_to_edit_the_particulars_of_an_employee_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;is&nbsp;Time/Card/Swipe/Punch&nbsp;ID&nbsp;under&nbsp;Employee&nbsp;personal&nbsp;information?&nbsp;', 'what_is_time_card_swipe_punch_id_under_employee_personal_information_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;does&nbsp;career&nbsp;Progression&nbsp;info&nbsp;works?&nbsp;', 'how_does_career_progression_info_works_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;Can&nbsp;the&nbsp;overtime&nbsp;rate&nbsp;be&nbsp;modified?&nbsp;', 'can_the_overtime_rate_be_modified_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;Can&nbsp;an&nbsp;employee&nbsp;be&nbsp;opted&nbsp;out&nbsp;for&nbsp;SDL&nbsp;contribution&nbsp;(Skill&nbsp;Development&nbsp;Levy)?&nbsp;', 'can_an_employee_be_opted_out_for_sdl_contribution_(skill_development_levy)_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;are&nbsp;funds&nbsp;amount&nbsp;calculated?&nbsp;', 'how_are_funds_amount_calculated_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;Can&nbsp;an&nbsp;employee&nbsp;contribute&nbsp;to&nbsp;multiple&nbsp;funds?&nbsp;', 'can_an_employee_contribute_to_multiple_funds_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;are&nbsp;current&nbsp;Leaves&nbsp;earned&nbsp;and&nbsp;why&nbsp;we&nbsp;need&nbsp;to&nbsp;key&nbsp;them?&nbsp;', 'what_are_current_leaves_earned_and_why_we_need_to_key_them_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;what&nbsp;are&nbsp;variables?&nbsp;Where&nbsp;we&nbsp;can&nbsp;use&nbsp;them?&nbsp;', 'what_are_variables__where_we_can_use_them_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;is&nbsp;FWL&nbsp;code?&nbsp;', 'what_is_fwl_code_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;is&nbsp;Workflow?&nbsp;', 'what_is_workflow_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;is&nbsp;Opt&nbsp;Out&nbsp;function?&nbsp;', 'what_is_opt_out_function_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;What&nbsp;is&nbsp;Worker&nbsp;Levy?&nbsp;', 'what_is_worker_levy_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;we&nbsp;can&nbsp;key&nbsp;in&nbsp;the&nbsp;Category&nbsp;name&nbsp;for&nbsp;the&nbsp;files&nbsp;to&nbsp;be&nbsp;uploaded?&nbsp;', 'how_we_can_key_in_the_category_name_for_the_files_to_be_uploaded_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;department&nbsp;to&nbsp;multiple&nbsp;employees?&nbsp;', 'how_to_key_in_department_and_designation_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;leave&nbsp;supervisor&nbsp;to&nbsp;multiple&nbsp;employees?&nbsp;', 'how_to_assign_leave_supervisor_to_multiple_employees_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;claim&nbsp;supervisor&nbsp;to&nbsp;multiple&nbsp;employees?&nbsp;', 'how_to_assign_claim_supervisor_to_multiple_employees_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;termination&nbsp;an&nbsp;employee?&nbsp;', 'what_is_the_termination_date_.htm'))
docAux = insDoc(xemployee_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;delete&nbsp;an&nbsp;Employee?&nbsp;', 'how_to_delete_an_employee_.htm'))
xclaims_management = insFld(foldersTree, gFld('&nbsp;Claims&nbsp;Management&nbsp;', 'claims_management.htm'))
xclaims_management.iconSrc = "images/pageicon_folder.gif"
xclaims_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xclaims_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;apply&nbsp;Claims&nbsp;', 'how_to_apply_claims.htm'))
xleave_management = insFld(foldersTree, gFld('&nbsp;Leave&nbsp;Management&nbsp;', 'leave_management.htm'))
xleave_management.iconSrc = "images/pageicon_folder.gif"
xleave_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;set&nbsp;up&nbsp;leave&nbsp;module?&nbsp;', 'how_to_set_up_leave_module_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Check&nbsp;remaing&nbsp;leaves?&nbsp;', 'how_to_check_remaing_leaves_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;add&nbsp;New&nbsp;Leave&nbsp;types?&nbsp;', 'how_to_add_new_leave_types_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;submit&nbsp;leave&nbsp;request?&nbsp;', 'how_to_submit_leave_request_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;leaves&nbsp;to&nbsp;the&nbsp;employees?&nbsp;', 'how_to_assign_leaves_to_the_employees_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;check&nbsp;the&nbsp;leave&nbsp;status,&nbsp;whether&nbsp;leave&nbsp;has&nbsp;been&nbsp;approved&nbsp;or&nbsp;Rejected?&nbsp;', 'how_to_check_the_leave_status__whether_leave_has_been_approved_or_rejected_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Delete&nbsp;applied&nbsp;leave/leaves?&nbsp;', 'how_to_delete_applied_leave_leaves_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Transfer&nbsp;Leaves?&nbsp;', 'how_to_transfer_leaves_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;do&nbsp;Add/Deduction&nbsp;of&nbsp;Leaves?&nbsp;', 'how_to_do_add_deduction_of_leaves_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Manage&nbsp;Holidays?&nbsp;', 'how_to_manage_holidays_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;Leave&nbsp;Supervisior?&nbsp;', 'how_to_assign_leave_supervisior_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Approve&nbsp;pending&nbsp;applied&nbsp;leaves?&nbsp;', 'how_to_approve_pending_applied_leaves_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;check&nbsp;monthly&nbsp;wise&nbsp;leave&nbsp;report?&nbsp;', 'how_to_check_monthly_wise_leave_report_.htm'))
docAux = insDoc(xleave_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;set&nbsp;Fixed&nbsp;Year&nbsp;Normal/FYPF/FYPC?&nbsp;', 'how_to_set_fixed_year_normal_fypf_fypc_.htm'))
xtimesheet_management = insFld(foldersTree, gFld('&nbsp;Timesheet&nbsp;Management&nbsp;', 'timesheet_management.htm'))
xtimesheet_management.iconSrc = "images/pageicon_folder.gif"
xtimesheet_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xtimesheet_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;import&nbsp;timesheet&nbsp;data?&nbsp;', 'how_to_import_timesheet_data_.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
xpayroll_management = insFld(foldersTree, gFld('&nbsp;Payroll&nbsp;Management&nbsp;', 'payroll_management.htm'))
xpayroll_management.iconSrc = "images/pageicon_folder.gif"
xpayroll_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;add&nbsp;New&nbsp;Addition&nbsp;Type?&nbsp;', 'how_to_add_new_addition_type_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;add&nbsp;New&nbsp;Deductions&nbsp;Type?&nbsp;', 'how_to_add_new_deductions_type_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;enable&nbsp;or&nbsp;disable&nbsp;OT1&nbsp;and&nbsp;OT2?&nbsp;', 'how_to_enable_or_disable_ot1_and_ot2_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Submit&nbsp;Payroll?&nbsp;', 'how_to_submit_payroll_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Approve&nbsp;Payroll?&nbsp;', 'how_to_approve_payroll_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Generate&nbsp;Payroll?&nbsp;', 'how_to_generate_payroll_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Print&nbsp;Payroll/Payslip&nbsp;one&nbsp;by&nbsp;one?&nbsp;', 'how_to_print_payroll_payslip_one_by_one_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Print&nbsp;Payslip&nbsp;for&nbsp;all&nbsp;employees&nbsp;in&nbsp;one&nbsp;shot?&nbsp;', 'how_to_print_payslip_for_all_employees_in_one_shot_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Unlock&nbsp;Payroll?&nbsp;', 'how_to_unlock_payroll_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Assign&nbsp;Payroll&nbsp;Supervisior,&nbsp;who&nbsp;can&nbsp;Approve/Reject&nbsp;Payoll?&nbsp;', 'how_to_assign_payroll_supervisior__who_can_approve_reject_payoll_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;What&nbsp;&nbsp;Payslip&nbsp;Format&nbsp;are&nbsp;available&nbsp;in&nbsp;the&nbsp;system?&nbsp;', 'what__payslip_format_are_available_in_the_system_.htm'))
docAux = insDoc(xpayroll_management, gLnk('R', '&nbsp;Can&nbsp;paylsip&nbsp;be&nbsp;sent&nbsp;by&nbsp;email?&nbsp;', 'can_paylsip_be_sent_by_email_.htm'))
xreports_management = insFld(foldersTree, gFld('&nbsp;Reports&nbsp;Management&nbsp;', 'reports_management.htm'))
xreports_management.iconSrc = "images/pageicon_folder.gif"
xreports_management.iconSrcClosed = "images/pageicon_folder.gif"
xcpf___central_provident_fund_ = insFld(xreports_management, gFld('&nbsp;CPF&nbsp;(&nbsp;Central&nbsp;Provident&nbsp;Fund)&nbsp;', 'cpf_(_central_provident_fund).htm'))
xcpf___central_provident_fund_.iconSrc = "images/pageicon_folder.gif"
xcpf___central_provident_fund_.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xcpf___central_provident_fund_, gLnk('R', '&nbsp;How&nbsp;to&nbsp;generate&nbsp;&&nbsp;submit&nbsp;CPF&nbsp;File?&nbsp;', 'how_to_generate___submit_cpf_file_.htm'))
xbank_transfer__giro_ = insFld(xreports_management, gFld('&nbsp;BANK&nbsp;TRANSFER&nbsp;(GIRO)&nbsp;', 'bank_transfer_(giro).htm'))
xbank_transfer__giro_.iconSrc = "images/pageicon_folder.gif"
xbank_transfer__giro_.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xbank_transfer__giro_, gLnk('R', '&nbsp;How&nbsp;to&nbsp;setup&nbsp;bank&nbsp;information&nbsp;for&nbsp;a&nbsp;company?&nbsp;', 'how_to_setup_bank_information_for_a_company_.htm'))
docAux = insDoc(xbank_transfer__giro_, gLnk('R', '&nbsp;What&nbsp;is&nbsp;value&nbsp;date&nbsp;in&nbsp;bank&nbsp;setup?&nbsp;', 'what_is_value_date_in_bank_setup_.htm'))
docAux = insDoc(xbank_transfer__giro_, gLnk('R', '&nbsp;How&nbsp;to&nbsp;setup&nbsp;bank&nbsp;information&nbsp;for&nbsp;an&nbsp;employee?&nbsp;', 'how_to_setup_bank_information_for_an_employee_.htm'))
docAux = insDoc(xbank_transfer__giro_, gLnk('R', '&nbsp;What&nbsp;bank&nbsp;formats&nbsp;are&nbsp;supported&nbsp;in&nbsp;smepayroll&nbsp;8.0?&nbsp;', 'what_bank_formats_are_supported_in_smepayroll_8.0_.htm'))
docAux = insDoc(xbank_transfer__giro_, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Generate&nbsp;Bank&nbsp;Giro&nbsp;File?&nbsp;', 'how_to_generate_bank_giro_file_.htm'))
xira8___related_forms = insFld(xreports_management, gFld('&nbsp;IRA8&nbsp;&&nbsp;related&nbsp;forms&nbsp;', 'ira8___related_forms.htm'))
xira8___related_forms.iconSrc = "images/pageicon_folder.gif"
xira8___related_forms.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xira8___related_forms, gLnk('R', '&nbsp;How&nbsp;to&nbsp;print&nbsp;IR8A&nbsp;forms&nbsp;for&nbsp;employees&nbsp;', 'how_to_print_ir8a_forms_for_employees.htm'))
docAux = insDoc(xira8___related_forms, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Generate&nbsp;&&nbsp;Submit&nbsp;IR8A&nbsp;Form?&nbsp;', 'how_to_generate___submit_ir8a_form_.htm'))
xadmin_management = insFld(foldersTree, gFld('&nbsp;Admin&nbsp;Management&nbsp;', 'admin_management.htm'))
xadmin_management.iconSrc = "images/pageicon_folder.gif"
xadmin_management.iconSrcClosed = "images/pageicon_folder.gif"
xmanage_company = insFld(xadmin_management, gFld('&nbsp;Manage&nbsp;company&nbsp;', 'manage_company.htm'))
docAux = insDoc(xmanage_company, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Add&nbsp;New&nbsp;Company?&nbsp;', 'how_to_add_new_comopany_.htm'))
docAux = insDoc(xmanage_company, gLnk('R', '&nbsp;Does&nbsp;the&nbsp;system&nbsp;support&nbsp;multiple&nbsp;CSN&nbsp;number&nbsp;for&nbsp;a&nbsp;company?&nbsp;', 'does_the_system_support_multiple_csn_number_for_a_company_.htm'))
xmanage_security = insFld(xadmin_management, gFld('&nbsp;Manage&nbsp;Security&nbsp;', 'manage_security.htm'))
xmanage_security.iconSrc = "images/pageicon_folder.gif"
xmanage_security.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xmanage_security, gLnk('R', '&nbsp;How&nbsp;to&nbsp;Assign&nbsp;Rights&nbsp;', 'how_to_assign_rights1.htm'))
docAux = insDoc(xadmin_management, gLnk('R', '&nbsp;Manage&nbsp;Settings&nbsp;', 'manage_settings.htm'))
docAux.iconSrc = "images/pageicon_folder.gif"
docAux = insDoc(xadmin_management, gLnk('R', '&nbsp;Manage&nbsp;Project&nbsp;', 'manage_project.htm'))
docAux.iconSrc = "images/pageicon_folder.gif"
xmanage_assignments1 = insFld(xadmin_management, gFld('&nbsp;Manage&nbsp;Assignments&nbsp;', 'manage_assignments1.htm'))
xmanage_assignments1.iconSrc = "images/pageicon_folder.gif"
xmanage_assignments1.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xmanage_assignments1, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;department&nbsp;to&nbsp;multiple&nbsp;employees?&nbsp;', 'how_to_bulk_assign_employees_to_department.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xmanage_assignments1, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;leave&nbsp;supervisor&nbsp;to&nbsp;multiple&nbsp;employees?&nbsp;', 'how_to_bulk_assign_employees_leave_supervisor.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
docAux = insDoc(xmanage_assignments1, gLnk('R', '&nbsp;How&nbsp;to&nbsp;assign&nbsp;claim&nbsp;supervisor&nbsp;to&nbsp;multiple&nbsp;employees?&nbsp;', 'how_to_bulk_assign_employees_claims_supervisor.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
xmanage_workflow = insFld(xadmin_management, gFld('&nbsp;Manage&nbsp;Workflow&nbsp;', 'manage_workflow.htm'))
docAux = insDoc(xmanage_workflow, gLnk('R', '&nbsp;How&nbsp;does&nbsp;workflow&nbsp;work?&nbsp;', 'how_does_workflow_work.htm'))
docAux.iconSrc = "images/pageicon_page.gif"
xinventory_management = insFld(foldersTree, gFld('&nbsp;Inventory&nbsp;Management&nbsp;', 'inventory_management.htm'))
xinventory_management.iconSrc = "images/pageicon_folder.gif"
xinventory_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xinventory_management, gLnk('R', '&nbsp;Manage&nbsp;Item&nbsp;', 'manage_item.htm'))
docAux.iconSrc = "images/pageicon_folder.gif"
docAux = insDoc(xinventory_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;transfer&nbsp;stock&nbsp;between&nbsp;2&nbsp;stores?&nbsp;', 'how_to_transfer_stock_between_2_stores_.htm'))
xinvoicing_management = insFld(foldersTree, gFld('&nbsp;Invoicing&nbsp;Management&nbsp;', 'invoicing_management.htm'))
xinvoicing_management.iconSrc = "images/pageicon_folder.gif"
xinvoicing_management.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xinvoicing_management, gLnk('R', '&nbsp;How&nbsp;to&nbsp;create&nbsp;an&nbsp;Invoice&nbsp;', 'how_to_create_an_invoice.htm'))
xFAQ = insFld(foldersTree, gFld('&nbsp;FAQ&nbsp;', 'FAQ.htm'))
docAux = insDoc(xFAQ, gLnk('R', '&nbsp;General&nbsp;FAQ&nbsp;', 'General_FAQ.htm'))
docAux = insDoc(xFAQ, gLnk('R', '&nbsp;Installation&nbsp;FAQ&nbsp;', 'Installation_FAQ.htm'))
