using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Data.SqlClient;
using Telerik.Web.UI;
using System.Net.Mail;
using System.Text;

namespace SMEPayroll.Cost
{

    public partial class CustomCostingReportNew_BusinessUnit : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                BindGrid();
            }


            for (int i = 0; i < RadGrid1.MasterTableView.AutoGeneratedColumns.Length; i++)
            {
                GridBoundColumn boundColumn = (RadGrid1.MasterTableView.AutoGeneratedColumns[i] as GridBoundColumn);
                if (boundColumn != null)
                {
                    if (boundColumn.DataType.Name == "Double" || boundColumn.DataType.Name == "Decimal")
                    {

                        //if (boundColumn.DataField.ToString() != "NH" & boundColumn.DataField.ToString() != "OT1" & boundColumn.DataField.ToString() != "OT2")//new condition for consolated Timesheet report
                        {
                            //if (boundColumn.DataField.ToString() == "SDL")
                            //{
                            //    boundColumn.DataType = Type.GetType("System.Double");
                            //    boundColumn.Aggregate = GridAggregateFunction.Sum;
                            //    boundColumn.DataFormatString = "{0:N5}";
                            //}
                            //else
                            {
                                boundColumn.DataType = Type.GetType("System.Double");
                                boundColumn.Aggregate = GridAggregateFunction.Sum;
                                boundColumn.DataFormatString = "{0:N2}";
                            }
                        }
                    }
                }

                RadGrid1.MasterTableView.Rebind();

            }

        }
        private void BindGrid()
        {
            DataSet dsFill = new DataSet();
            dsFill = (DataSet)Session["CostingDataset1"];

            this.RadGrid1.DataSource = dsFill;
            this.RadGrid1.DataBind();



        }

        string header;
        protected void RadGrid1_ColumnCreated(object sender, Telerik.Web.UI.GridColumnCreatedEventArgs e)
        {
            if (e.Column.UniqueName != "Department" && e.Column.UniqueName != "ExpandColumn" && e.Column.UniqueName != "Emp_Code" && e.Column.UniqueName != "FullName" && e.Column.UniqueName != "time_card_no")
            {
               // string sqlQ = "select Businessunit from cost_businessunit where Bid=" + e.Column.UniqueName + "";
                string sqlQ = "select Businessunit from " + Request.QueryString["cat"].ToString() + " where Bid=" + e.Column.UniqueName + "";
                

                SqlDataReader dr = DataAccess.ExecuteReader(CommandType.Text, sqlQ, null);
                if (dr.HasRows)
                {
                    while (dr.Read())
                    {
                        header = Utility.ToString(dr.GetValue(0));
                    }

                    e.Column.HeaderText = header;
                }

            }
        }



        protected void RadGrid1_ItemDataBound(object sender, GridItemEventArgs e)
        {
            if (e.Item is GridDataItem)
            {
                GridDataItem item = e.Item as GridDataItem;
                foreach (GridColumn col in RadGrid1.MasterTableView.AutoGeneratedColumns)
                {

                    if (item[col.UniqueName].Text == "0.00")
                    {
                        item[col.UniqueName].Text = "";
                    }

                }
            }
        }


    }
}
