//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.TimeSheet {
    
    public partial class ManualTimesheetCompare {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.ScriptManager SM1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hiddenmsg;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr1;
        protected Telerik.Web.UI.RadDatePicker rdStart;
        protected Telerik.Web.UI.RadDatePicker rdEnd;
        protected System.Web.UI.WebControls.DropDownList cmbEmp;
        protected System.Web.UI.WebControls.DropDownList drpSubProject;
        protected System.Web.UI.WebControls.CheckBox chkempty;
        protected System.Web.UI.WebControls.ImageButton imgbtnfetch;
        protected Telerik.Web.UI.RadCodeBlock RadCodeBlock1;
        protected Telerik.Web.UI.RadGrid RadGrid1;
        protected System.Web.UI.WebControls.Label lblMsg;
    }
}
