//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Leaves {
    
    public partial class LeavesAllowed {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList drpGroup;
        protected System.Web.UI.WebControls.DropDownList drpLeaveType;
        protected System.Web.UI.WebControls.TextBox TextBox1;
        protected System.Web.UI.WebControls.TextBox txtmindays;
        protected System.Web.UI.WebControls.DropDownList drpenable;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
